[package]
name = "zlijadb-crdt"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CRDT merge layer for zlijadb"
publish = false

[dependencies]
zlijadb-storage.workspace = true
automerge.workspace = true
# yrs.workspace = true   # بديل إذا اخترت yrs بدل automerge
serde.workspace = true
thiserror.workspace = true