[package]
name = "zlijadb-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Delta sync protocol for zlijadb"
publish = false

[dependencies]
zlijadb-core.workspace = true
zlijadb-crdt.workspace = true
tokio.workspace = true
serde.workspace = true
thiserror.workspace = true